<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Cityzen" failures="1" tests="4" name="Test" time="0.085" errors="0" timestamp="2024-06-10T18:50:40 EDT">
  <testcase classname="failedTestRetry.FailedTestA" name="test1" time="0.01"/>
  <testcase classname="failedTestRetry.FailedTestA" name="test2" time="0.01">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="failedTestRetry.FailedTestA" name="test2" time="0.002">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase classname="failedTestRetry.FailedTestA" name="test2" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at failedTestRetry.FailedTestA.test2(FailedTestA.java:15)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
</testsuite> <!-- Test -->
